name = "memory-verses"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "memory-verses-db"
database_id = "3df1d236-58e2-49bb-9f99-920a13027f4e"
