// Runs before every build (npm's "prebuild" lifecycle hook) so public/version.json
// always matches src/data/version.js — this is what the running app polls to detect
// that a newer build has been deployed (PWAs saved to the home screen have no
// browser chrome to hard-refresh from otherwise).
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const src = readFileSync(new URL('../src/data/version.js', import.meta.url), 'utf8');
const match = src.match(/APP_VERSION\s*=\s*['"]([^'"]+)['"]/);
if (!match) throw new Error('Could not find APP_VERSION in src/data/version.js');

writeFileSync(
  new URL('../public/version.json', import.meta.url),
  JSON.stringify({ version: match[1] }) + '\n'
);

// Total commit count, shown in the About panel as "updated N times" — a
// small, honest way to convey the amount of work behind the app. Computed
// fresh locally (full git history), then committed like a normal source
// file. Remote CI builds (e.g. Cloudflare's) may only have a shallow clone,
// which would compute a much smaller, wrong number — so this only ever
// overwrites the committed value with a LARGER one, never regresses it.
const commitCountPath = new URL('../src/data/commitCount.js', import.meta.url);
let previousCount = 0;
try {
  const prev = readFileSync(commitCountPath, 'utf8');
  const prevMatch = prev.match(/COMMIT_COUNT\s*=\s*(\d+)/);
  if (prevMatch) previousCount = parseInt(prevMatch[1], 10);
} catch { /* first run — no existing file */ }

let commitCount = null;
try {
  const computed = parseInt(execSync('git rev-list --count HEAD', { cwd: new URL('..', import.meta.url) }).toString().trim(), 10);
  if (Number.isFinite(computed)) commitCount = Math.max(computed, previousCount);
} catch { /* not a git checkout — leave null */ }
if (commitCount === null && previousCount > 0) commitCount = previousCount;

writeFileSync(
  commitCountPath,
  `// Auto-generated by scripts/write-version.mjs at build time. Do not edit.\nexport const COMMIT_COUNT = ${commitCount === null ? 'null' : commitCount};\n`
);
